services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db
    ports:
      - "5412:5432"
    networks:
      - db-network
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data



networks:
  db-network:

volumes:
  postgres_data:
  redis:
