[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
exclude = "(venv_test_horand/|.*__init__\\.py$|core/)"
ignore_missing_imports = false


[tool.black]
line-length = 100
target-version = ["py311"]
skip-string-normalization = false
exclude = "(venv_test_horand/|.*__init__\\.py$|core/)"
